export default CONSTANTS = {
  ENTER_YOUR_MOBILE_NUM: 'Enter your \nmobile number',
  ENTER_NUMBER_HERE: 'Enter number here',
  WE_WILL_SEND_CON_CODE: 'We will send you confirmation code',
  NEXT: 'Next',
  VERIFY: 'Verify',
  ENTER_CODE_SENT: 'Enter code sent \nto your phone',
  WE_SENT_IT_TO: 'We sent it to the number ',
  ADD: 'Add',
  NOT_REGISTERED: 'Not Registered',
  PHONE_NUM: 'Phone Number',
  CAMERA: 'Camera',
  REMOVE: 'Remove',
  PHOTOS: 'Photos',
  CANCEL: 'Cancel',
  EMAIL: 'Email',
  NAME: 'Name',
  BACK: 'Back',
  RECOMMENDED_FOR_YOU: 'Recommended for you',
  NUMBER: 'Number',
  ACHIEVEMENTS: 'Achievements',
  LOG_OUT: 'Log Out',
  LOGIN: 'Login',
  PRIVACY: 'Privacy',
  OTP: 'Otp',
  TRENDING: 'Trending',
  START: 'Start',
};
