export default ICONS = {
  homeOutline: 'home',
  exam: 'book',
  person: 'person',
  search: 'md-search-sharp',
  time: 'md-time-outline',
  rating: 'star',
  back: 'chevron-back-sharp',
  camera_outline: 'camera-outline',
  power: 'md-power-sharp',
  forward: 'md-chevron-forward',
  picture: 'image',
  bin: 'trash',
  email: 'email',
  edit: 'edit',
  settings: 'settings',
  call: 'call',
  lock: 'lock',
  notification: 'notifications',
  notificationOff: 'notifications-off',
  deleteNumber: 'md-close-sharp',
};
